on:
  pull_request:
    branches:
      - master

name: 'lint'

jobs:
  lint-scripts:
    name: lint-scripts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: './scripts'
        severity: error
